name: local_database
description: A local database using dart:io file system components. Comes with put, get, and remove functionality.
version: 1.2.0
homepage: https://github.com/Blakexx/local_database

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  queue: ^2.0.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter